language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DELIMIDENT=n DOWNLOAD_VERSION=1210FC5de
  - DELIMIDENT=y DOWNLOAD_VERSION=1210FC5de
  - DELIMIDENT=n DOWNLOAD_VERSION=1170FC8de
  - DELIMIDENT=y DOWNLOAD_VERSION=1170FC8de
  - DELIMIDENT=n DOWNLOAD_VERSION=1150fc9de
  - DELIMIDENT=y DOWNLOAD_VERSION=1150fc9de

sudo: true

before_install:
  - sudo apt-get update -qq 
  - sudo apt-get install aria2 curl -y
  - travis_retry export DOWNLOAD_LINK=$(phantomjs --ssl-protocol=tlsv1 ./tests/ci/travis/download.js | tail -1 | grep http)
  - travis_retry aria2c -x 16 ${DOWNLOAD_LINK}
  - DOWNLOAD_FILE=$(ls iif*.tar)
  - sudo chmod +x ./tests/ci/travis/*.sh
  - sudo ./tests/ci/travis/informix_install.sh ${DOWNLOAD_FILE}
  - sudo ./tests/ci/travis/informix_start.sh
  - export INFORMIXDIR=/opt/IBM/informix
  - git clone https://git.php.net/repository/pecl/database/pdo_informix.git
  - (cd pdo_informix/; phpize && ./configure --with-pdo-informix=${INFORMIXDIR} && make && sudo make install)

install:
  - echo "extension=pdo_informix.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m | grep -i pdo
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0" --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - sed -i "s/DELIMIDENT=\w/DELIMIDENT=${DELIMIDENT}/g" tests/data/config.php

script:
  - phpunit -v
